### ISSUE TITLE
Error on the first startup

### ISSUE THREAD

**Issue by adferga** [rakshitbharat/very-simple-attendance#3]
Hello, during the first startup, I encounter the following issue. Is there something I can do?

![error](https://github.com/user-attachments/assets/226eb722-2a43-466b-8d06-9950335a838b)

Thanks.

**Comment by rakshitbharat** [comment]
Please use docker based approach or check the docker file to know all requirements 
I think this is node version issue 
Because if the build is passing in vercil then it can be your env issue

**Comment by rakshitbharat** [comment]
> Hello, during the first startup, I encounter the following issue. Is there something I can do?
> 
> ![error](https://private-user-images.githubusercontent.com/190091063/392510386-226eb722-2a43-466b-8d06-9950335a838b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTc2NDIsIm5iZiI6MTczNDE5NzM0MiwicGF0aCI6Ii8xOTAwOTEwNjMvMzkyNTEwMzg2LTIyNmViNzIyLTJhNDMtNDY2Yi04ZDA2LTk5NTAzMzVhODM4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxNzI5MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzAwOWE1OTY4ZDU2ZGEwOWM3NmFiODRjYmIzZDZmZTRhNzQ2NzBiODNmYWJiZWVmZGNhNDBlMDk0NzdiZTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vGcpuwIjyTfDrDI1yZR7hxKe7j6Cjm5-9DNS8lWUueQ)
> 
> Thanks.

I am closing it for now if it don’t be solved with above suggestions please reopen it I will check 

Thanks

**Comment by rakshitbharat** [comment]
> Hello, during the first startup, I encounter the following issue. Is there something I can do?
> 
> ![error](https://private-user-images.githubusercontent.com/190091063/392510386-226eb722-2a43-466b-8d06-9950335a838b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNjA4NDcsIm5iZiI6MTczNDI2MDU0NywicGF0aCI6Ii8xOTAwOTEwNjMvMzkyNTEwMzg2LTIyNmViNzIyLTJhNDMtNDY2Yi04ZDA2LTk5NTAzMzVhODM4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxMTAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWI3NDU3MThjMTE5NmM2YmVhYzY0OWVmNWRhZjYwNDVjNTY1YTgxY2UxZjBjNzk2OTM4YjkwMzQ4ZTM4MjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tZYV8W_EV6Rl_LJFD9NQM__STg6ojDHJQm7hldRvTc8)
> 
> Thanks.

please check latest source with 1.1v we have updated docker files to fix the build issue
